export const ListIntems = [
    { name: "Bolso Pañalera"},
    { name: "Lima eléctrica para uños"},
    { name: "Extractor de leche entrada doble electricos"},
    { name: "Cama cuna"},
    { name: "Colecho o Moisés"},
    { name: "Pañales Huggies etapa 0 / 5"},
    { name: "Pañitos húmedos"},
    { name: "Tetero marca avent"},
    { name: "Tetero marca avent"},
    { name: "Tetero marca avent"},
    { name: "Chupa tetero marca avent"},
    { name: "Chupa tetero marca avent"},
    { name: "Chupa tetero marca avent"},
    { name: "Chupo"},
    { name: "Monitor con cámara bebé"},
    { name: "Almohada recién nacidos"},
    { name: "Calentador de teteros"},
    { name: "Cojín de lactancia ( x )"},
    { name: "Tapete de fichas acolchado"},
    { name: "Paquete de bolas piscina"},
    { name: "Crema desitin"},
    { name: "Sonajero"},
    { name: "Móvil"},
    { name: "Rascaencia"},
    { name: "Cepillo de seda para peinarlo"},
    { name: "Loción para bebé"},
    { name: "Shampoo para bebé"},
    { name: "Jabón líquido"},
    { name: "Crema para bebé"},
    { name: "Babero plástico"},
    { name: "Babero tela"},
    { name: "Casco gateador"},
    { name: "Rodilleras"},
    { name: "Bolsas para banco de leche"},
    { name: "Bolsas para banco de leche"},
    { name: "Bolsas para banco de leche"},
    { name: "Saco para dormir bby fresh"},
    { name: "Cobija"},
    { name: "Cambiador portátil"},
    { name: "Sácamocos"},
    { name: "Piscina inflable"},
    { name: "Saco para dormir"},
    { name: "Toallas"},
    { name: "jaula patio de juegos portatil"},
    { name: "Lámpara musical"},
    { name: "Alfombra de entretenimiento"},
    { name: "Gorritos"},
    { name: "Medias"},
    { name: "Mitones"},
    { name: "Ropa"},
    { name: "Termómetro para agua"},
    { name: "Juguetes"},
    { name: "Papelera/basura pañales"},
    { name: "Juegues de estimulación temprana"},
    { name: "Vajilla para bebé anti reguero"},
    { name: "Espejo retrovisor para el carro"},
    { name: "Horimiya"},
    ];